#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Twist
def callback(data):
    rospy.loginfo("%f %f %f %f %f", data.linear.x, data.linear.y,
                  data.linear.z, data.angular.x, data.angular.y)
    pub = rospy.Publisher('uno', Twist, queue_size=10)
    a=data.linear.x
    b=data.linear.y
    d3=data.linear.z
    val = Twist()
    val.linear.x=a
    val.linear.y=b
    

    pub.publish(val) 
def listener():

    # In ROS, nodes are uniquely named. If two nodes with the same
    # name are launched, the previous one is kicked off. The
    # anonymous=True flag means that rospy will choose a unique
    # name for our 'listener' node so that multiple listeners can
    # run simultaneously.
    rospy.init_node('listener', anonymous=True)
    pub = rospy.Publisher('uno', Twist, queue_size=10)
    rospy.Subscriber('cmd_vel', Twist, callback)

    # spin() simply keeps python from exiting until this node is stopped
    rospy.spin()



if __name__ == '__main__':    
    listener()
